# Single source of truth for the build plan: every Claude Code session, its dependencies,
# what to give it and what it hands on. Generates the doc tables and the kit briefs.

WAVES = {
    0: "Wave 0 · Decide and freeze",
    1: "Wave 1 · Foundation",
    2: "Wave 2 · Shared core",
    3: "Wave 3 · First real data, and the Meta review build",
    4: "Wave 4 · YouTube, X, and Facebook in development mode",
    5: "Wave 5 · Approval-gated platforms and the client portal",
    6: "Wave 6 · Insight layer",
    7: "Wave 7 · Amber vendor routes (optional)",
}

SIZE = {"S": "one sitting", "M": "1 to 2 days with review", "L": "3 to 5 days with review"}

def S(id, title, wave, track, size, builds, needs=(), give=(), produces=(), alongside=(),
      services=(), anytime=None, deadline=None, traps=(), human=None, kind="service", critical=False):
    return dict(id=id, title=title, wave=wave, track=track, size=size, builds=builds, needs=list(needs),
                give=list(give), produces=list(produces), alongside=list(alongside), services=list(services),
                anytime=anytime, deadline=deadline, traps=list(traps), human=human, kind=kind, critical=critical)

SESSIONS = [
# ---------------- Wave 0 ----------------
S("D1", "Contract inventory", 0, "Decide", "M",
  "One inventory of every topic, job queue, table, column, budget tag, flag and retention class the 86 PRDs use, with every conflict between them",
  give=["all 86 PRDs", "CONVENTIONS.md", "README decisions 1 to 9", "OPEN-QUESTIONS.md"],
  produces=["docs/contracts/INVENTORY.md (each topic: producers, consumers, fields per PRD; each table: columns, writers, readers; each job queue: producer and consumer)",
            "docs/contracts/CONFLICTS.md (each disagreement, where it appears, the options)"],
  alongside=["F1", "the external applications in section 2"],
  traps=["Have one subagent per PRD folder extract its rows, then merge and cross-check in the main session",
         "Several pollers publish tier changes on source.events, while registry-writer otherwise owns that topic: list every writer of every topic",
         "Tables or columns named in a single PRD (for example retention_audit, profile_cache, news_sites) must appear in the inventory",
         "The same field under different names in different PRDs is a conflict, not a synonym"],
  kind="decision", critical=True),
S("D2", "Decisions and contract freeze", 0, "Decide", "M",
  "ADRs for the 9 proposed decisions, the foundation choices and every conflict; CONVENTIONS v1.1",
  needs=["D1"],
  give=["INVENTORY.md and CONFLICTS.md", "README decisions 1 to 9", "the foundation choices list (section 2)"],
  produces=["docs/decisions/ADR-0001... (one decision each, with options and consequences)",
            "docs/prds/_shared/CONVENTIONS.md v1.1 with the addendum and decisions folded in",
            "docs/decisions/DEFERRED.md (every open question not decided now, with the session that must settle it)"],
  alongside=["F1"],
  traps=["Claude interviews you with AskUserQuestion; it proposes, you decide",
         "Do not let a decision hide in a PRD edit: every change to a PRD cites its ADR"],
  human="You, for the whole session", kind="decision", critical=True),
S("D3", "Specs for the parts with no PRD", 0, "Decide", "M",
  "PRDs in the same 14-section template for the query API, client portal (onboarding, OAuth connect, keywords and sources, review queue, provenance, deletion requests), dashboard (with the Meta App Review slice) and admin console, with the n8n flows (one per channel and per card type, ADR-0067)",
  needs=["D2"],
  give=["CONVENTIONS v1.1", "the review requirements of Meta, LinkedIn and TikTok (section 2)", "the 86 PRDs' section 4 (who consumes what)"],
  produces=["docs/prds/apps/query-api.md", "docs/prds/apps/client-portal.md", "docs/prds/apps/dashboard.md", "docs/prds/apps/admin-console.md"],
  anytime="after D2", deadline="before Q1 (Wave 3)",
  traps=["The App Review slice must show analytics on named Pages; a raw data pipeline or a 'monitoring' framing fails review",
         "The admin console's register screen shows every `permitted_uses` row for the user's review and writes each change audited; a use with no row is allowed (ADR-0068)"],
  human="You, interview mode", kind="spec"),

# ---------------- Wave 1 ----------------
S("F1", "Repository, toolchain, local stack, CI, Claude kit", 1, "Foundation", "M",
  "pnpm and Turborepo monorepo, TypeScript strict, Vitest, uv with ruff and pytest, docker compose (Redpanda, Supabase local, ClickHouse, SeaweedFS for S3), CI, the docs tree; fits the kit's check script, make targets and hooks to the toolchain",
  give=["the kit and the PRDs, committed to main on day zero (KIT-README.md)"],
  produces=["make up, make check, make test, make e2e", "services/_template", "docs/ tree with the PRDs, conventions and the kit's templates",
            "CI on every pull request: make check on changed packages; handoff and closed review present for service changes; contract paths only on a contract-change label; a docs/dependencies.md line for each new dependency; scripts/check-fixtures.sh for scrubbed fixtures",
            "Per-worktree test namespaces (topic prefix, Postgres schema, ClickHouse database)"],
  alongside=["D1", "D2"],
  traps=["Pin versions: Node LTS, pnpm, Python, uv, Redpanda, ClickHouse, Supabase CLI",
         "Tests in parallel worktrees share one local stack: derive a TEST_NAMESPACE from the worktree name for topics, Postgres schemas and ClickHouse databases",
         "MinIO's community edition is no longer published; use SeaweedFS or Garage for local S3"],
  kind="foundation", critical=True),
S("F2", "Contracts package", 1, "Foundation", "L",
  "Zod schemas for every topic, job and envelope; JSON Schema export; Pydantic models for Python; valid and invalid fixtures; idempotency key and item_id derivation with golden vectors; TypeScript and Python conformance tests",
  needs=["D2", "F1"],
  give=["INVENTORY.md", "the ADRs", "CONVENTIONS v1.1", "every PRD's section 6.2 example message"],
  produces=["packages/contracts v1.0.0", "fixtures/contracts/ with valid and invalid examples for every topic", "docs/contracts/VERSIONING.md (additive within a version; breaking change = new version with a dual-publish window)"],
  alongside=["F3", "F7"],
  traps=["When PRD examples disagree on a field, the ADR decides, never a majority of examples",
         "Keys must be byte-identical in TypeScript and Python: fix Unicode normalisation and JSON canonicalisation in the golden vectors",
         "Every data payload carries provenance (route, vendor, service, fetched_at) and retention_class; jobs, `jobs.completed` and `source.events` carry `producer` (ADR-0003)"],
  kind="foundation", critical=True),
S("F3", "Control-plane schema", 1, "Foundation", "L",
  "Supabase migrations for every control-plane table, indexes, row-level security, the column ownership map, generated types and seed data",
  needs=["D2", "F1"],
  give=["INVENTORY.md (tables)", "the ADRs", "CONVENTIONS registry, cursors and qualifier sections"],
  produces=["supabase/migrations v1", "docs/contracts/TABLE-OWNERS.md (which service writes which column)", "generated TypeScript types", "seed scripts for tests and staging"],
  alongside=["F2", "F7", "F8"],
  traps=["Client users see only their clients' rows; services use the service role",
         "Advisory-lock keys for leader election must be unique per service",
         "Seed the comment series profiles and budget tags from the conventions tables, not by hand",
         "Seed `permitted_uses` with the 'not allowed' rows ADR-0068 lists (YouTube video and audio downloads; Facebook and Instagram training), each with its clause: YouTube's terms for the two downloads; for Facebook and Instagram training, the user's own choice, the user's answer of 9 Oct 2026 ('Start as not allowed'). A missing row means allowed, so only the seed keeps an excluded use out (ADR-0068)"],
  kind="foundation", critical=True),
S("F4", "SDK runtime (Node)", 1, "Foundation", "L",
  "listening-sdk core: producer and consumer partitioned by source_id, envelope validation, job wrapper with retries and DLQ, cursor advance after ack, jobs.completed reports, structured logs, Prometheus metrics, health, config and Vault, control-plane client, service generator",
  needs=["F2", "F3"],
  give=["CONVENTIONS idempotency, error-handling and observability sections", "ADRs on the Kafka client and jobs.completed", "fb-page-feed-poller PRD as the reference consumer"],
  produces=["packages/listening-sdk v0.1", "pnpm new:service <name> generating a service that passes make check"],
  alongside=["F7", "F8"],
  traps=["A cursor never advances before the producer acknowledges the batch",
         "Backoff 30 s to 15 min with jitter, 5 attempts, then dlq.<service> and an alert",
         "Prove with a test that no token or secret can reach a log line",
         "ADR-0008's mapper registry, keyed (service, api_version), is in listening-sdk; record in your handoff where the registry sits in the package and how a mapper registers in it, so that C4 can decide from it where producers' mappers sit (DEFERRED.md section 3)",
         "The comment in services/_template/src/adapter.ts L3-L4 still says 401 and 403 mark the route degraded; reword it to ADR-0021's rule: 401 and 403 are classified by reason, an authorisation one setting credential or source state, never a route state, and stopping the batch (ADR-0021)"],
  kind="foundation", critical=True),
S("F5", "SDK scheduling, quota client, adapter kit, fake platform", 1, "Foundation", "L",
  "Rotation scheduler with leader election, quota client, HTTP adapter base with the error policy, canary hook, per-host gate, fake clock, and a scriptable fake-platform server",
  needs=["F4"],
  give=["fb-page-feed-poller section 5.1 (the rotation reference)", "quota-governor section 6 (allowance API)", "source-health-canary section 5 (canary hook)", "news-robots-checker (host gate)", "CONVENTIONS rotation and error sections"],
  produces=["listening-sdk v0.2", "fake-platform harness with scenarios: pagination, 429, 401 and 403, empty 200, schema drift, edits, deletions"],
  alongside=["F6", "F7", "F8"],
  traps=["Each service's due time is next_due_at in its own cursors row, set from the start of the last poll; order by it then tier; most stale first when behind, with rotation_behind (ADR-0015, ADR-0041)",
         "401 and 403 are classified by reason: a quota one waits for the reset, an item-scoped one ends that item, an authorisation one marks the credential revoked or the source blocked and stops the batch, never a route state (ADR-0021); the kit never rotates accounts or IPs",
         "Empty-200 responses are counted per route for the canary"],
  kind="foundation", critical=True),
S("F6", "Python SDK twin", 1, "Foundation", "M",
  "The Python subset of the SDK: consumer and producer, envelope, job wrapper, DLQ, jobs.completed, logs, metrics, health, config",
  needs=["F2", "F4"],
  give=["F4 handoff", "contracts JSON Schemas and the conformance suite"],
  produces=["py/listening_sdk v0.1 passing the shared conformance suite"],
  alongside=["F5", "F8"],
  traps=["Same retry, DLQ and cursor semantics as Node, proved by shared tests, not by reading"],
  kind="foundation"),
S("F7", "Text fold and golden corpus", 1, "Foundation", "M",
  "The Arabic and Sorani folds in TypeScript exactly as lang-dialect-id section 5.3 C defines them, tokenizer helpers, and a golden corpus both languages' code must pass",
  needs=["D2", "F1"],
  give=["lang-dialect-id PRD (detection, fold table, /v1/fold)", "keyword-matcher and normalize-item PRDs (text_norm use)"],
  produces=["packages/text v1", "fixtures/text/golden.jsonl (500 or more cases: Iraqi Arabic, MSA, Sorani, mixed, English, emoji, URLs, hashtags, digits)"],
  alongside=["F2", "F3", "F4", "F5", "F8"],
  traps=["Language is decided on the raw text first; the fold depends on it (yaa folds in opposite directions for Arabic and Sorani)",
         "Sorani-only letters (ڕ ڵ ۆ ێ ە) must survive the fold",
         "Arabizi is not transliterated (documented gap)"],
  human="An Iraqi Arabic and Sorani reader reviews the golden file", kind="foundation", critical=True),
S("F8", "ClickHouse schema", 1, "Foundation", "M",
  "Migrations for items, comments, analysis, metrics_timeseries, aggregates_hourly, sources_dim, keywords_dim and hits; month partitions; TTL by retention class; text index on text_norm; migration runner",
  needs=["D2", "F2"],
  give=["store-writer, aggregator and retention-purger PRDs", "CONVENTIONS analytics store and retention classes"],
  produces=["clickhouse/migrations v1", "query smoke tests"],
  alongside=["F3", "F4", "F5", "F6", "F7"],
  traps=["Upserts keyed on item_id need an explicit version column (ReplacingMergeTree or equivalent) so a replay never wins over a newer edit",
         "Raw text TTLs differ by retention class; item-level derived rows follow their item's class; aggregates keep ten years, per-channel YouTube rollups 36 months (ADR-0054, ADR-0056)"],
  kind="foundation"),
S("I1", "Infrastructure (staging first)", 1, "Infra", "L",
  "Hetzner servers, network and firewall, the cluster, Redpanda, ClickHouse, buckets with lifecycle rules, TLS ingress for webhooks, image registry, deploy pipeline, backups",
  needs=["D2"],
  give=["CONVENTIONS deployment section", "ADRs on the cluster and object storage", "the list of public endpoints (Facebook, Instagram, LinkedIn and Telegram webhooks, YouTube PubSubHubbub)"],
  produces=["staging environment", "infra/ as code (OpenTofu plus cluster manifests)", "runbook for deploy, rollback and restore"],
  anytime="after D2", deadline="before G2",
  traps=["Run this session in Manual permission mode and review every plan and apply",
         "TLS from Let's Encrypt; no dependency on Cloudflare (flagged in the vendor screen)",
         "The Telegram webhook endpoint must be outside Iraq (tg PRDs)"],
  human="You approve every infrastructure change", kind="infra"),
S("I2", "Observability", 1, "Infra", "M",
  "Prometheus, Grafana dashboards per service family, logs, alert rules for the SLOs, alert routing through n8n",
  needs=["I1", "F4"],
  give=["CONVENTIONS observability section", "each PRD's section 10 (metrics and alerts)"],
  produces=["dashboards: rotation lag, staleness p95, DLQ, quota denied, cost units", "alert routes to Telegram or Slack through n8n"],
  anytime="after I1 and F4", deadline="before G2", kind="infra"),
S("G0", "Gate: foundation", 1, "Gates", "S",
  "Run the foundation gate and write its report",
  needs=["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8"],
  produces=["docs/gates/G0.md"], kind="gate", critical=True),

# ---------------- Wave 2 ----------------
S("C0", "Reference vertical on the fake platform", 2, "Core", "M",
  "ref-poller, ref-comments-fetcher, ref-resolver and ref-search against the fake platform, using every SDK feature once; the adapter pattern note",
  needs=["F5", "G0"],
  give=["fb-page-feed-poller and fb-post-comments-fetcher PRDs as the models", "F5 handoff"],
  produces=["services/ref-* (test-only, never deployed)", "docs/patterns/ADAPTER-PATTERN.md: the copy-me guide for every platform session"],
  alongside=["C1", "C2", "C3", "C7"],
  traps=["Every behaviour a platform service needs (rotation, catch-up, quota wait, 429, 401, empty 200, DLQ, backfill hand-over, comment-series report) appears here once"],
  kind="core", critical=True),
S("C1", "quota-governor", 2, "Core", "M", "Allowance API, budgets and reservations, priorities 1 to 5, modes normal, stretch and exhausted",
  services=["quota-governor"], needs=["F5", "G0"],
  give=["ADR on priorities and modes (decision 2)", "canonical budget tags (CONVENTIONS addendum)"],
  produces=["budget seed configuration per tag"], alongside=["C0", "C2", "C3", "C7"],
  traps=["The +24 h comment step is held, never cancelled", "Amber intervals stretch but never beyond 24 h",
         "The X and Instagram ledgers' rules land with X1 and IG2; this session builds the generic ledger support"]),
S("C2", "raw-archiver", 2, "Core", "M", "Archive of raw.items to object storage, raw_ref, replay reader",
  services=["raw-archiver"], needs=["F4", "G0"],
  give=["CONVENTIONS object-storage layout", "local SeaweedFS bucket"],
  produces=["archive reader for replays (normalize-item, lang-dialect-id, analysis)"], alongside=["C0", "C1", "C3", "C7"],
  traps=["Commit offsets only after the object is durable", "Raw payloads can hold personal data: deletions must reach them (C13)"]),
S("C3", "lang-dialect-id", 2, "Core", "M", "POST /v1/detect and /v1/fold: language ID, dialect scores, Arabic and Sorani folds, model versions",
  services=["lang-dialect-id"], needs=["F6", "F7", "G0"],
  give=["F7 golden corpus", "pinned model bundle (fastText lid.176, CAMeL Tools, KLPT)"],
  produces=["service passing the fold conformance suite", "lang_model_version scheme"], alongside=["C0", "C1", "C2", "C7"],
  traps=["Detect on raw text, then fold by language", "dialect describes the text, never the author or the country"],
  human="A reader of Iraqi Arabic and Sorani checks 50 random outputs"),
S("C7", "registry-writer", 2, "Core", "M", "The single writer of the registry: applies decisions and client and ops changes, publishes source.events",
  services=["registry-writer"], needs=["F4", "F3", "G0"],
  give=["qualifier rules (CONVENTIONS)", "ADR on writers of source.events (from D1 and D2)"],
  produces=["source.events stream", "change API for the admin console and client portal"], alongside=["C0", "C1", "C2", "C3"],
  traps=["Applying the same decision twice changes nothing", "Rejected candidates are remembered 180 days"]),
S("C4", "normalize-item (core)", 2, "Core", "L", "Mapper registry, one schema for every platform, the lang call with fallback, dedup, edits and versions, parking of unknown shapes",
  services=["normalize-item"], needs=["F4", "F7", "C2"],
  give=["C3 API contract (stub it until C3 merges)", "C0 record shapes"],
  produces=["items.normalized", "docs/patterns/MAPPERS.md: how each platform session adds its mapper"], alongside=["C5", "C6"],
  traps=["Only the fake platform's mapper here; each platform session adds its own", "When lang-dialect-id is down: lang = und with the TypeScript fold and lang_pending",
         "Unknown shapes are archived and parked as schema_unknown, never dropped",
         "Where mappers live: ADR-0008 puts the registry keyed (service, api_version) in listening-sdk, the kit puts mappers under services/normalize-item/src/mappers/<platform>/; MAPPERS.md names the one place, decided from F4's handoff, before wave 3 (DEFERRED.md section 3)"], critical=True),
S("C5", "keyword-matcher", 2, "Core", "M", "Keyword compile through /v1/fold, matching on text_norm, every keyword hit on item.hits, discovery.hits for candidates only (ADR-0031)",
  services=["keyword-matcher"], needs=["F4", "F7", "F8", "G0"],
  give=["C3 /v1/fold contract", "keywords table (F3)"], alongside=["C4", "C6"],
  traps=["keyword-matcher is the only writer of item.hits, one per item, client and keyword whoever the poster is; it writes discovery.hits only for candidates, beside the other candidate writers (ADR-0031)"]),
S("C6", "store-writer", 2, "Core", "M", "Upserts of items, comments, analysis and metrics into ClickHouse; dimensions from the control plane",
  services=["store-writer"], needs=["F4", "F8", "G0"], alongside=["C4", "C5"],
  traps=["A deleted item never reappears on replay", "Retention fields set on every row"]),
S("C8", "poster-resolver", 2, "Core", "M", "Candidate dedup by candidate_key, dispatch to the platform resolver, poster.profiles",
  services=["poster-resolver"], needs=["F5", "C0"],
  give=["C0 ref-resolver (stands in for platform resolvers)"], alongside=["C9", "C10", "C11"],
  traps=["Candidates arrive from discovery.hits and from searches that emit directly: dedup by candidate_key", "Private individuals are never profiled: an ordinary individual's poster.profiles answer (account_type individual, not public) is minimised and keyed by author_ref, with no handle, name or URL; a public account's, creator's or public figure's answer carries its identity fields (ADR-0010, ADR-0033)"]),
S("C9", "qualifier", 2, "Core", "M", "The ten qualifier rules, review cards through n8n, registry.decisions",
  services=["qualifier"], needs=["F4", "F3", "C1", "G0"],
  give=["qualifier rules (CONVENTIONS)", "n8n webhook for review cards, or a stub"], alongside=["C8", "C10", "C11"],
  traps=["A review left 24 h defaults to reject", "Route caps and budgets are checked through quota-governor"]),
S("C10", "backfill-orchestrator", 2, "Core", "M", "90-day backfill on add, route caps, backfill_status, hand-over to rotation",
  services=["backfill-orchestrator"], needs=["F5", "C7", "C1"],
  give=["ADR on backfill_status (decision 4)", "fb-backfill PRD (hand-over pattern)"], alongside=["C8", "C9", "C11"],
  traps=["Single writer of backfill_status", "A failed or slow backfill ends capped and the source joins the rotation anyway"]),
S("C11", "comment-decay-scheduler", 2, "Core", "L", "Comment series per route, armed early stop, extension, hot posts, reply and metrics jobs, driven by jobs.completed",
  services=["comment-decay-scheduler"], needs=["F5", "F3", "C1", "G0"],
  give=["comment series table (CONVENTIONS addendum)", "ADRs for decisions 1 to 3", "C0 ref-comments-fetcher reports"],
  produces=["comment_series rows", "jobs for every comment, reply and metrics service"], alongside=["C8", "C9", "C10"],
  traps=["Only this service emits comment, reply and metrics jobs", "Early stop is armed after 5 stored comments or the +24 h step",
         "On amber routes, hot-post extras go first above 80% of budget"], critical=True),
S("C12", "source-health-canary", 2, "Core", "M", "Canaries per route, empty-200 rate, health state machine, fallback decisions with government scope",
  services=["source-health-canary"], needs=["F5", "C7"],
  give=["ADR-0021 (fallback scope; it supersedes README decision 5)", "canary_targets"], alongside=["C13", "C14", "C15"],
  traps=["Route-wide states come only from the canary; a blocked source falls back to its vendor automatically where that flag is on, with an n8n notice to ops, never an approval card (ADR-0021)", "A green source a government client watches never falls back to amber; a client-owned property falls back under the same conditions as any other source, with the n8n notice to ops (ADR-0021)"]),
S("C13", "deletion-propagator", 2, "Core", "M", "Deletions to every store: ClickHouse, archive, aggregates, alerts",
  services=["deletion-propagator"], needs=["F8", "C2", "C6"], alongside=["C12", "C15"],
  traps=["Deletion must reach archive objects (rewrite or tombstone)", "Mode withhold and author scope are needed by x-compliance-sync"]),
S("C14", "retention-purger", 2, "Core", "M", "Time-based purges per retention class, client offboarding, retention audit",
  services=["retention-purger"], needs=["C13"],
  give=["retention classes (CONVENTIONS)"], alongside=["C12", "C15"],
  traps=["linkedin_48h, youtube_30d_text, news_excerpt and x_24h_sync each work differently", "Purge by class: raw text on its class's clock, item-level derived rows (scores, hits, metrics) with their item; aggregates keep ten years and per-channel YouTube rollups 36 months, by F8's TTLs (ADR-0054, ADR-0056)"]),
S("C15", "aggregator", 2, "Core", "M", "Hourly and daily aggregates from base tables and derived scores, watermark for alerts",
  services=["aggregator"], needs=["C6", "F8"], alongside=["C12", "C13", "C14"],
  traps=["Aggregates rebuild from base tables after deletions", "YouTube figures stay per channel owner except where the carve-out allows totals; per-channel YouTube rollups keep 36 months and cross-owner ones ten years until counsel answers (ADR-0048, ADR-0056)"]),
S("E1", "End-to-end suite for G1", 2, "Core", "L",
  "tests/e2e/G1: the twelve G1 scenarios against the fake platform, the synthetic-load scenario, and the make e2e GATE=G1 target",
  needs=["C0", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14", "C15"],
  give=["build-plan/GATES.md (the G1 checks)", "C0 handoff (fake-platform scenarios)", "CONVENTIONS rotation, comment series and SLO sections"],
  produces=["tests/e2e/G1 kept as the regression suite", "make e2e GATE=G1"],
  traps=["The suite drives the real core services with the fake platform and the fake clock; no service code changes here, failures become issues for their owners",
         "Simulated time (48 hours of rotation, 30 days of comment series) runs on the fake clock, not wall time"],
  kind="core", critical=True),
S("G1", "Gate: fake platform end to end", 2, "Gates", "M",
  "Run the twelve end-to-end scenarios on the fake platform and write the report",
  needs=["E1"],
  produces=["docs/gates/G1.md"], kind="gate", critical=True),

# ---------------- Wave 3: news ----------------
S("N0", "News probe and seed list", 3, "News", "M", "Per-site capability report and recorded fixtures for 20 to 30 Iraqi outlets",
  needs=["F1"], give=["your list of news websites", "news PRDs section 5.3"],
  produces=["docs/probes/news.md (robots, feeds, sitemaps, news sitemaps, challenges, comment systems per site)", "fixtures/news/<host>/"],
  anytime="after F1", deadline="before N1",
  traps=["Obey robots.txt, Content Signals, RSL and 402 in the probe too", "One connection per host, 2 to 5 s apart"],
  human="You supply the website list", kind="probe"),
S("N1", "news-robots-checker", 3, "News", "M", "Crawl policies per host (robots, Content Signals, RSL, 402) and the host gate wiring",
  services=["news-robots-checker"], needs=["F5", "N0", "G1"], give=["N0 report and fixtures", "ADR on the host gate (decision 6)"],
  traps=["Policy precedence exactly as the PRD orders it", "Every news service reads crawl.policies before fetching"]),
S("N2", "news-site-resolver", 3, "News", "M", "Resolves candidate domains into news sources",
  services=["news-site-resolver"], needs=["N1", "C8", "C9", "C3"], give=["C8 resolver dispatch contract"]),
S("N3", "news-feed-poller", 3, "News", "M", "RSS and Atom polling on rotation into article.urls",
  services=["news-feed-poller"], needs=["N1", "N2"], give=["N0 feed fixtures", "C0 adapter pattern"], alongside=["N4", "N5", "N6"]),
S("N4", "news-sitemap-poller", 3, "News", "M", "News and regular sitemaps on rotation into article.urls",
  services=["news-sitemap-poller"], needs=["N1", "N2"], give=["N0 sitemap fixtures"], alongside=["N3", "N5", "N6"]),
S("N5", "news-homepage-differ", 3, "News", "M", "Homepage diffs for sites with no feed or sitemap",
  services=["news-homepage-differ"], needs=["N1", "N2"], give=["N0 homepage fixtures", "the shared Playwright Chromium pool"], alongside=["N3", "N4", "N6"]),
S("N6", "news-article-extractor (Python)", 3, "News", "L", "Article fetch and extraction with trafilatura; 7-day full-text cache; the news mapper",
  services=["news-article-extractor"], needs=["F6", "N1", "N0"], give=["N0 article fixtures", "C4 mapper guide"],
  produces=["news mapper in normalize-item", "text_full_ref cache"], alongside=["N3", "N4", "N5"],
  traps=["Beyond 7 days keep the excerpt and metadata only (news_excerpt)", "Proxies only for challenged hosts and only in the news crawler"]),
S("N7", "news-dedup", 3, "News", "M", "Story clustering and duplicates across outlets into news.dedup",
  services=["news-dedup"], needs=["N6", "C4"], give=["ADR on news.dedup (decision 6)"]),
S("N8", "news-comments-fetcher", 3, "News", "M", "Disqus comment series for the sites that use it",
  services=["news-comments-fetcher"], needs=["N6", "C11"], anytime="after N6 and C11", deadline="before news go-live, if your sites use Disqus"),
# ---------------- Wave 3: web ----------------
S("W0", "Web search probe", 3, "Web", "S", "Recorded results for 30 keywords from Perplexity, Mojeek, GDELT and Common Crawl",
  needs=["F1"], give=["Perplexity and Mojeek keys", "30 real client keywords (Arabic, Sorani, English)"],
  produces=["docs/probes/web.md", "fixtures/web/"], anytime="after F1", deadline="before W1", kind="probe"),
S("W1", "web-search-perplexity", 3, "Web", "M", "Keyword searches on rotation through the Perplexity Search API",
  services=["web-search-perplexity"], needs=["F5", "C1", "W0", "G1"], alongside=["W2"],
  traps=["Budget perplexity_search; up to 5 queries per request", "Search output rule: items to raw.items with source_id = the keyword rule"]),
S("W2", "web-search-mojeek", 3, "Web", "M", "Keyword searches on rotation through Mojeek Business",
  services=["web-search-mojeek"], needs=["F5", "C1", "W0", "G1"], alongside=["W1", "W3"]),
S("W3", "search-hit-router", 3, "Web", "M", "Routes search results to poster-resolver, news-site-resolver and article.urls",
  services=["search-hit-router"], needs=["W1", "C8", "N2"], alongside=["W2"]),
S("W4", "web-gdelt-poller", 3, "Web", "S", "GDELT DOC API polling for Iraqi coverage",
  services=["web-gdelt-poller"], needs=["W3"], anytime="after W3"),
S("W5", "web-commoncrawl-scanner", 3, "Web", "M", "Monthly Common Crawl scan for new Iraqi sites",
  services=["web-commoncrawl-scanner"], needs=["W3", "N2"], anytime="after W3 and N2"),
# ---------------- Wave 3: Meta review build ----------------
S("FB0", "Meta probe (development mode)", 3, "Facebook", "M", "Recorded Graph API responses for every Facebook and Instagram call shape the PRDs use",
  needs=["F1"], give=["the Meta app (Business Verification under way)", "team test Pages and Instagram professional accounts with roles on the app", "FB and IG PRDs section 5.3"],
  produces=["docs/probes/meta.md", "fixtures/facebook/", "fixtures/instagram/"], anytime="after F1 and the Meta app exist", deadline="before FB1",
  traps=["Unapproved features work only for people with a role on the app", "Record /feed pagination at limit=100, comments with filter=stream (no ids), reactions summaries, Pages Search, Business Discovery, webhook payloads",
         "Scrub commenter names and ids before saving"], kind="probe", critical=True),
S("FB1", "fb-page-resolver", 3, "Facebook", "M", "Resolves Facebook Page candidates into profiles",
  services=["fb-page-resolver"], needs=["FB0", "C8", "G1"], critical=True),
S("FB2", "fb-page-feed-poller", 3, "Facebook", "L", "Page posts on rotation through /feed; the Facebook mapper",
  services=["fb-page-feed-poller"], needs=["FB1", "C1", "C11"], give=["FB0 fixtures", "C0 adapter pattern", "C11 handoff (job kinds, series_step)", "C4 mapper guide"],
  produces=["Facebook mapper in normalize-item", "post_ref format used by FB3, FB4, FB5"], alongside=["Q1"],
  traps=["About 600 ranked posts per Page per year on /feed", "Error 80001 means too many calls to this Page", "System-user token per client, injected per job"], critical=True),
S("Q1", "Query API v0", 3, "Apps", "M", "Read endpoints over ClickHouse with client scoping through Supabase Auth",
  needs=["D3", "C6", "C15", "G1"], give=["query-api PRD (D3)", "F8 schema"], alongside=["FB2"], kind="app", critical=True),
S("U1", "Dashboard slice for Meta App Review", 3, "Apps", "M", "Screens comparing named Pages, engagement over time and post lists; the screencast script",
  needs=["Q1", "FB2"], give=["dashboard PRD (D3)", "Meta review requirements (section 2)"],
  produces=["the analytics screens Meta must see", "docs/approvals/meta-screencast.md"],
  human="You record the screencast and submit App Review the day this merges", kind="app", critical=True),
S("E2", "Gate tooling for staging", 3, "Infra", "M",
  "Scripts and queries the G2 to G4 checks run: SLO reports, cost reconciliation, crawl-policy audit, restore drill, per-platform compliance checks, synthetic load at 1.5 times full scale through the fake platform",
  needs=["G1", "I1", "I2"], give=["build-plan/GATES.md (G2, G3 and G4 checks)", "I1 and I2 handoffs", "CONVENTIONS observability and retention sections"],
  produces=["tools/gates/ with one runnable script or query per check", "make gate-report GATE=<G>"],
  anytime="after G1, I1 and I2", deadline="before G2",
  traps=["Read-only against staging except the load generator and the restore drill, which run only in a scratch environment",
         "Each platform's compliance check is a stub until that platform's session fills it in; G3 fails while a stub remains"],
  kind="infra"),
S("G2", "Gate: staging with real data", 3, "Gates", "M", "72-hour staging soak of news and web on real data; data-quality sample; costs; restore drill",
  needs=["N1", "N2", "N3", "N4", "N5", "N6", "N7", "W1", "W2", "W3", "E2"], produces=["docs/gates/G2.md"], kind="gate"),

# ---------------- Wave 4: YouTube ----------------
S("YT0", "YouTube probe", 4, "YouTube", "S", "Recorded Data API and PubSubHubbub responses, with quota costs observed",
  needs=["F1"], give=["the API key", "10 Iraqi channels you will watch"], produces=["docs/probes/youtube.md", "fixtures/youtube/"],
  anytime="after F1", deadline="before YT1", kind="probe"),
S("YT1", "yt-channel-resolver", 4, "YouTube", "M", "Resolves channel candidates and handles into channel ids",
  services=["yt-channel-resolver"], needs=["YT0", "C8", "G1"]),
S("YT2", "yt-pubsub-receiver", 4, "YouTube", "M", "PubSubHubbub subscriptions and notifications for new uploads",
  services=["yt-pubsub-receiver"], needs=["YT1", "I1"], alongside=["YT3", "YT4"]),
S("YT3", "yt-uploads-reconciler", 4, "YouTube", "M", "Uploads-playlist reconciliation on rotation",
  services=["yt-uploads-reconciler"], needs=["YT1"], alongside=["YT2", "YT4"]),
S("YT4", "yt-video-details-fetcher", 4, "YouTube", "M", "videos.list details and +24 h and +7 d metrics; the YouTube mapper",
  services=["yt-video-details-fetcher"], needs=["YT1", "C11"], produces=["YouTube mapper in normalize-item"], alongside=["YT2", "YT3"]),
S("YT5", "yt-comments-fetcher", 4, "YouTube", "M", "commentThreads.list on the YouTube comment series",
  services=["yt-comments-fetcher"], needs=["YT4", "C11"]),
S("YT6", "yt-replies-fetcher", 4, "YouTube", "M", "comments.list for threads above the reply threshold",
  services=["yt-replies-fetcher"], needs=["YT5"]),
S("YT7", "yt-text-purger", 4, "YouTube", "M", "30-day deletion or refresh of YouTube text",
  services=["yt-text-purger"], needs=["YT5", "C14"], deadline="before YouTube data reaches staging",
  traps=["Comment text, titles and descriptions have no exemption from the 30 days"]),
S("YT8", "yt-keyword-search", 4, "YouTube", "M", "search.list within the 100-a-day bucket",
  services=["yt-keyword-search"], needs=["YT1", "YT4", "C1"]),
S("YT9", "yt-web-search-bridge", 4, "YouTube", "S", "YouTube URLs from the web search engines",
  services=["yt-web-search-bridge"], needs=["W1", "W2", "YT1"], anytime="after W1, W2 and YT1"),
# ---------------- Wave 4: X ----------------
S("X0", "X probe", 4, "X", "S", "Recorded responses for every X call shape, with a spending cap",
  needs=["F1"], give=["X developer app on pay-per-use, with a spending cap", "20 Iraqi accounts and 10 keywords"],
  produces=["docs/probes/x.md", "fixtures/x/"], anytime="after F1", deadline="before X1",
  traps=["Every read costs money: cap the probe"], kind="probe"),
S("X1", "x-recent-search", 4, "X", "L", "Keyword search on rotation; the read ledger; the X mapper",
  services=["x-recent-search"], needs=["X0", "C1", "C5", "G1"], produces=["x_read_ledger semantics used by every X service", "X mapper in normalize-item"],
  traps=["Charges deduplicate per resource per UTC day; 3,000,000 post reads per billing cycle"]),
S("X2", "x-user-resolver", 4, "X", "M", "Resolves account candidates", services=["x-user-resolver"], needs=["X1", "C8"], alongside=["X3"]),
S("X3", "x-user-timeline-poller", 4, "X", "M", "Registered accounts' timelines on rotation", services=["x-user-timeline-poller"], needs=["X1"], alongside=["X2"]),
S("X4", "x-filtered-stream", 4, "X", "M", "Filtered stream with up to 1,000 rules", services=["x-filtered-stream"], needs=["X1", "X3"]),
S("X5", "x-full-archive-search", 4, "X", "M", "Backfill, keyword history and the X reply steps to day 30 from the full archive (ADR-0059, ADR-0064)", services=["x-full-archive-search"], needs=["X1", "C10"]),
S("X6", "x-replies-fetcher", 4, "X", "M", "Replies and quotes by conversation_id on the X series", services=["x-replies-fetcher"], needs=["X3", "C11"]),
S("X7", "x-compliance-sync", 4, "X", "M", "Batch compliance mirrored into every store", services=["x-compliance-sync"], needs=["X0", "C13", "C14", "G1"],
  deadline="before X data reaches staging", traps=["Deletions and withholds mirrored within 24 hours of X's signal"]),
# ---------------- Wave 4: Facebook continues ----------------
S("FB3", "fb-backfill", 4, "Facebook", "M", "90-day backfill with cursor hand-over to the poller", services=["fb-backfill"], needs=["FB2", "C10"], alongside=["FB4", "FB5"]),
S("FB4", "fb-reactions-fetcher", 4, "Facebook", "M", "Reaction summaries at +24 h and +7 d", services=["fb-reactions-fetcher"], needs=["FB2", "C11"], alongside=["FB3", "FB5"]),
S("FB5", "fb-post-comments-fetcher", 4, "Facebook", "L", "Comment series with hash keys (no ids under PPCA), edits and sweeps", services=["fb-post-comments-fetcher"], needs=["FB2", "C11"], alongside=["FB3", "FB4"],
  traps=["Identical comments in the same second collide by design: measure, do not hide"]),
S("FB6", "fb-page-search", 4, "Facebook", "M", "Pages Search by keyword into discovery.hits", services=["fb-page-search"], needs=["FB1", "C8"], anytime="after FB1"),
S("G3", "Gate: platform go-live (repeat per platform)", 4, "Gates", "M", "Per-platform go-live checklist on staging",
  needs=["G2"], produces=["docs/gates/G3-<platform>.md"], kind="gate"),
S("G4", "Gate: production readiness", 5, "Gates", "M", "Security review, restore drill, 24 hours of synthetic load at 1.5 times full scale, counsel sign-off, on-call",
  needs=["G2", "E2"], produces=["docs/gates/G4.md"], anytime="after G2 and the first G3", deadline="before the first client sees data", kind="gate"),

# ---------------- Wave 5 ----------------
S("U2", "Client portal", 5, "Apps", "L", "Onboarding, OAuth connect (Facebook Login for Business, LinkedIn, TikTok), keywords and sources, review queue, provenance statement, deletion requests",
  needs=["D3", "Q1"], give=["client-portal PRD (D3)", "LinkedIn and TikTok review requirements (section 2)"],
  produces=["OAuth flows the LinkedIn and TikTok screencasts must show"], kind="app", critical=True),
S("FB7", "fb-client-webhook-receiver", 5, "Facebook", "M", "Webhooks for client-owned Pages", services=["fb-client-webhook-receiver"], needs=["FB2", "U2", "I1"]),
S("IG1", "ig-account-resolver", 5, "Instagram", "M", "Business Discovery resolution of account candidates", services=["ig-account-resolver"], needs=["FB0", "C8", "G1"], alongside=["IG2"]),
S("IG2", "ig-hashtag-search", 5, "Instagram", "M", "Hashtag search within the 30-per-7-days ledger", services=["ig-hashtag-search"], needs=["FB0", "C1", "C8", "G1"], alongside=["IG1"],
  traps=["30 unique hashtags per Instagram business account per 7 days"]),
S("IG3", "ig-account-media-poller", 5, "Instagram", "L", "Account media on rotation and metrics; the Instagram mapper", services=["ig-account-media-poller"], needs=["IG1", "C11"], produces=["Instagram mapper in normalize-item"]),
S("IG4", "ig-webhook-receiver", 5, "Instagram", "M", "Webhooks for client accounts", services=["ig-webhook-receiver"], needs=["IG3", "U2", "I1"]),
S("IG5", "ig-mentions-fetcher", 5, "Instagram", "M", "Mentions of client accounts", services=["ig-mentions-fetcher"], needs=["IG4"], alongside=["IG6"]),
S("IG6", "ig-own-comments-fetcher", 5, "Instagram", "M", "Comment series on client media", services=["ig-own-comments-fetcher"], needs=["IG3", "IG4", "C11"], alongside=["IG5"]),
S("LI0", "LinkedIn probe (Development tier)", 5, "LinkedIn", "S", "Recorded Community Management API responses on your own test Page",
  needs=["F1"], give=["Development tier approval", "your test Page with you as super admin"], produces=["docs/probes/linkedin.md", "fixtures/linkedin/"],
  anytime="after F1 and Development tier approval", deadline="before LI1", kind="probe"),
S("LI1", "li-client-posts-poller", 5, "LinkedIn", "M", "Client page posts on rotation; the LinkedIn mapper", services=["li-client-posts-poller"], needs=["LI0", "U2", "C14"],
  produces=["LinkedIn mapper in normalize-item"], traps=["Member data purged after 48 hours; nothing exported to clients"]),
S("LI2", "li-own-comments-fetcher", 5, "LinkedIn", "M", "Comment series on client posts", services=["li-own-comments-fetcher"], needs=["LI1", "C11"]),
S("LI3", "li-notification-receiver", 5, "LinkedIn", "M", "Webhook notifications for client pages", services=["li-notification-receiver"], needs=["LI1", "LI2", "I1"]),
S("TG0", "Telegram probe", 5, "Telegram", "S", "Recorded Bot API updates from a test channel and its discussion group",
  needs=["F1"], give=["a bot from BotFather", "a test channel and discussion group where the bot is admin"], produces=["docs/probes/telegram.md", "fixtures/telegram/"],
  anytime="after F1", deadline="before TG1", kind="probe"),
S("TG1", "tg-bot-channel-receiver", 5, "Telegram", "M", "Channel posts pushed to our bot; the Telegram mapper", services=["tg-bot-channel-receiver"], needs=["TG0", "I1", "C8", "G1"], produces=["Telegram mapper in normalize-item"]),
S("TG2", "tg-discussion-receiver", 5, "Telegram", "M", "Comments from linked discussion groups", services=["tg-discussion-receiver"], needs=["TG1", "C11"]),
S("TT0", "TikTok Display probe (sandbox)", 5, "TikTok", "S", "Recorded Display API responses from sandbox accounts",
  needs=["F1"], give=["TikTok developer app with a sandbox"], produces=["docs/probes/tiktok.md", "fixtures/tiktok/"],
  anytime="after F1", deadline="before TT1", kind="probe"),
S("TT1", "tt-client-videos-fetcher", 5, "TikTok", "M", "Client-authorised accounts' videos and metrics; the TikTok mapper", services=["tt-client-videos-fetcher"], needs=["TT0", "U2"],
  produces=["TikTok mapper in normalize-item"]),

# ---------------- Wave 6 ----------------
S("A0", "Labelled evaluation set", 6, "Insight", "M", "Annotation guide (interviewing you), sampling and export scripts, agreement computation, frozen splits and the evaluation harness; annotators then label 2,000 or more Iraqi items outside Claude Code",
  needs=["D2"], give=["samples exported from staging (after G2)", "the analysis PRDs' label sets"],
  produces=["docs/analysis/ANNOTATION-GUIDE.md", "tools/eval/ (sampling, export, agreement, split freezing, evaluation harness) with tests", "fixtures/eval/ with train, dev and test splits once labelling is done"],
  anytime="after D2 (real samples after G2)", deadline="before A1", human="Annotators who read Iraqi Arabic, Sorani and Badini", kind="data"),
S("A1", "analysis-sentiment", 6, "Insight", "L", "Two-lane sentiment scoring into items.analysis", services=["analysis-sentiment"], needs=["F6", "C4", "A0", "G1"],
  give=["ADR on GPU pool or model API", "ADR on analysis lanes and items.analysis/v1 (decision 7)"], alongside=["A2", "A3", "A4"]),
S("A2", "analysis-topics", 6, "Insight", "L", "Topic classification against the taxonomy", services=["analysis-topics"], needs=["F6", "C4", "A0", "G1"], give=["taxonomy seed"], alongside=["A1", "A3", "A4"]),
S("A3", "analysis-entities", 6, "Insight", "L", "Entity and brand linking against the knowledge base", services=["analysis-entities"], needs=["F6", "C4", "A0", "G1"], give=["knowledge-base seed (entities, aliases, brand assets)"], alongside=["A1", "A2", "A4"]),
S("A4", "analysis-media", 6, "Insight", "L", "Images, thumbnails, OCR, frame OCR and speech-to-text on media the register of permitted uses does not exclude; YouTube thumbnails only (ADR-0068)", services=["analysis-media"], needs=["F6", "C4", "G1"], give=["A3 brand ids when available"], alongside=["A1", "A2", "A3"]),
S("A5", "alert-evaluator", 6, "Insight", "M", "Alert rules over the aggregate views, metrics_timeseries and item_stories, routed through n8n (ADR-0047, ADR-0048)", services=["alert-evaluator"], needs=["C15", "C5", "G1", "A1", "A2", "A3", "A4"], anytime="after C15, C5, G1 and A1 to A4 (ADR-0048)"),
S("U3", "Full dashboard", 6, "Apps", "L", "The client dashboard over the query API, with analysis views", needs=["Q1", "U2", "A1", "A2"], kind="app"),

# ---------------- Wave 7: amber ----------------
S("VFB0", "Facebook vendor probe", 7, "Amber", "S", "Recorded vendor responses (SociaVault or ScrapeCreators) and billing behaviour", needs=["F5", "G2"], give=["signed vendor contract", "FB_VENDOR_ROUTE value"], kind="probe"),
S("VFB1", "fb-keyword-search", 7, "Amber", "M", "Vendor keyword search of Facebook posts", services=["fb-keyword-search"], needs=["VFB0", "C5", "C8"]),
S("VFB2", "fb-group-posts-poller", 7, "Amber", "M", "Vendor-sourced group posts on rotation", services=["fb-group-posts-poller"], needs=["VFB0", "C10", "C11"]),
S("VFB3", "fb-group-comments-fetcher", 7, "Amber", "M", "Vendor-sourced group comments", services=["fb-group-comments-fetcher"], needs=["VFB2", "C11"]),
S("VIG0", "Instagram vendor probe", 7, "Amber", "S", "Recorded SociaVault responses", needs=["F5", "G2"], give=["signed vendor contract", "IG_VENDOR_ROUTE value"], kind="probe"),
S("VIG1", "ig-keyword-search", 7, "Amber", "M", "Vendor keyword search on Instagram", services=["ig-keyword-search"], needs=["VIG0", "IG2"]),
S("VIG2", "ig-comments-fetcher", 7, "Amber", "M", "Vendor comments on non-client media", services=["ig-comments-fetcher"], needs=["VIG0", "IG3", "C11"]),
S("VTT0", "TikTok vendor probe", 7, "Amber", "S", "Recorded TikHub or EnsembleData responses", needs=["F5", "G2"], give=["signed vendor contract", "TT_VENDOR_ROUTE value"], kind="probe"),
S("VTT1", "tt-keyword-search", 7, "Amber", "M", "Vendor keyword search on TikTok", services=["tt-keyword-search"], needs=["VTT0", "C5"]),
S("VTT2", "tt-hashtag-feed-poller", 7, "Amber", "M", "Vendor hashtag feeds on rotation", services=["tt-hashtag-feed-poller"], needs=["VTT0"]),
S("VTT3", "tt-user-resolver", 7, "Amber", "M", "Vendor profile resolution", services=["tt-user-resolver"], needs=["VTT0", "C8"]),
S("VTT4", "tt-profile-videos-poller", 7, "Amber", "M", "Creator videos on rotation", services=["tt-profile-videos-poller"], needs=["VTT3", "C10", "C11"]),
S("VTT5", "tt-video-comments-fetcher", 7, "Amber", "M", "Comment series with commenters hashed in the adapter", services=["tt-video-comments-fetcher"], needs=["VTT4", "C11"], alongside=["VTT6"]),
S("VTT6", "tt-video-stats-refresher", 7, "Amber", "M", "+24 h and +7 d video stats", services=["tt-video-stats-refresher"], needs=["VTT4", "C11"], alongside=["VTT5"]),
S("VLI0", "LinkedIn vendor probe", 7, "Amber", "S", "Recorded harvestapi Actor responses on Apify", needs=["F5", "G2"], give=["Apify contract", "LI_VENDOR_ROUTE value"], kind="probe"),
S("VLI1", "li-post-search", 7, "Amber", "M", "Vendor post search", services=["li-post-search"], needs=["VLI0", "C5"]),
S("VLI2", "li-org-resolver", 7, "Amber", "M", "Company page resolution", services=["li-org-resolver"], needs=["VLI0", "C8"]),
S("VLI3", "li-company-posts-poller", 7, "Amber", "M", "Company page posts on rotation", services=["li-company-posts-poller"], needs=["VLI2", "C10", "C11", "C14"]),
S("VLI4", "li-post-comments-fetcher", 7, "Amber", "M", "Vendor comments on company posts", services=["li-post-comments-fetcher"], needs=["VLI3", "C11"]),
S("VTG0", "Telegram vendor probe", 7, "Amber", "S", "Recorded Telemetrio and Apify Actor responses", needs=["F5", "G2"], give=["Telemetrio and Apify contracts, author notice", "TG_VENDOR_ROUTE and TG_POSTS_ACTOR values"], kind="probe"),
S("VTG1", "tg-message-search", 7, "Amber", "M", "Telemetrio message search", services=["tg-message-search"], needs=["VTG0", "C5"]),
S("VTG2", "tg-channel-resolver", 7, "Amber", "M", "Channel resolution and stats", services=["tg-channel-resolver"], needs=["VTG0", "C8"]),
S("VTG3", "tg-channel-posts-poller", 7, "Amber", "M", "Channel posts through the Apify Actor on rotation", services=["tg-channel-posts-poller"], needs=["VTG2", "C10", "C11"]),
]

EXTRA_ALONGSIDE = {
    "X7": ["X1", "X2", "X3"], "X4": ["X5", "X6"], "X5": ["X6"],
    "YT5": ["YT8"], "YT6": ["YT7", "YT8"], "YT7": ["YT8"],
    "FB6": ["FB3", "FB4", "FB5"],
    "N7": ["N3", "N4", "N5"], "N8": ["N7"],
    "IG2": ["IG3"],
}
_by = {x["id"]: x for x in SESSIONS}
for a, bs in EXTRA_ALONGSIDE.items():
    for b in bs:
        if b not in _by[a]["alongside"]: _by[a]["alongside"].append(b)
# make alongside symmetric
for x in SESSIONS:
    for b in list(x["alongside"]):
        if b in _by and x["id"] not in _by[b]["alongside"]:
            _by[b]["alongside"].append(x["id"])

BY_ID = {s["id"]: s for s in SESSIONS}
